name: Auto Deploy Node.js to EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
 #     - name: Checkout repo
  #      uses: actions/checkout@v3

      - name: Deploy to Ubuntu instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/nodejsrepo
            git pull origin main
            npm install
            pm2 restart app || pm2 start npm --name "app" -- start
